name: gdb-docs-updater

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * 0' # every Sunday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.8

      - name: setup SSH keys
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: execute build_docs.py
        run: python build_docs.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _readthedocs
          git commit -m "update gdb docs"
          
      - name: push changes
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build_docs
