name: gdb-docs-updater

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: execute build_docs.py
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python build_docs.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _readthedocs
          git commit -m "update gdb docs"
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: amd-master
